# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'dashboard' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for dashboard
  pod 'libPusher', git: 'https://github.com/pusher/libPusher.git', branch: 'push-notifications'

end

# Auth0 Lock

pod 'Lock', '~> 1.26'
pod 'Lock/TouchID'
pod 'Lock/SMS'
pod 'Lock/Email'
